# Generated by Django 5.1 on 2024-08-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lisence',
            new_name='License',
        ),
    ]
