# Generated by Django 5.1 on 2024-08-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0002_rename_lisence_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='descripion',
            new_name='description',
        ),
    ]
