# Generated by Django 5.1 on 2024-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0003_rename_descripion_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
